name: Benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.10"

      - uses: actions/setup-node@v6
        with:
          token: ${{ secrets.GH_DOTCOM_TOKEN }}
          node-version: 25

      - name: Bun install
        run: bun install

      - name: Build prod
        env:
          PATH: /usr/local/bin:/usr/bin:/bin
        run: |
          bun run prod

      - name: Benchmark Bun
        env:
          PATH: /usr/local/bin:/usr/bin:/bin
        run: |
          bun --expose-gc scripts/benchmark.js

      - name: Benchmark Node
        run: |
          node --expose-gc scripts/benchmark.js
